### ISSUE TITLE
An item with the same key has already been added. Key: Microsoft.NETCore.App NBitcoin.NETCore.Tests 1

### ISSUE THREAD

**Issue by andbene72** [tom-corwin/NBitcoin#4]
Have you an idea why happen ?
Tried to tweak json file with no success in solving it.

![image](https://cloud.githubusercontent.com/assets/6141792/17294687/897ce19e-57f8-11e6-81ec-d880be5beaf7.png)

**Comment by tom-corwin** [comment]
Nunit tests are still in early prerelease stages, so I'm not concerned about having a functioning Tests project for it. I will update it when the NUnit package supports the latest prerelease of the Microsoft.NETCore.App package.

**Comment by tom-corwin** [comment]
I haven't been able to find a workaround for it, but I'm hoping when NETCore 1.0.1 is released, this is fixed.
